### ISSUE TITLE
Ivan's issue queue

### ISSUE THREAD

**Issue by subotic** [dasch-swiss/knora-api#580]
What I'm currently working on, in descending order of priority:

#### Operations
- [ ] implement centralized logging
- [ ] implement monitoring #2 

#### Development
- [ ] list admin (#511) 
    - [x] PR #572 
    - [x] issue: https://github.com/dhlab-basel/Salsah/issues/28
    - [x] PR https://github.com/dhlab-basel/Salsah/pull/35
- [ ] Built-in groups #679
- [ ] The groups endpoint should return all (custom and built-in) groups (#587) 
- [ ] Have `webapi` send JWT to Sipi for auth (#520)
    - [ ] Authentication for Sipi missing when logging into Salsah (#92)
    - [ ] Try to use an HTTP Interceptor to add JWT tokens to the header for each image call to SIPI (https://github.com/dhlab-basel/Salsah/issues/157)
- [ ] Try Stardog #618
- [ ] Try AllegroGraph #619
- [ ] add project metadata ontology and extend V2 API (#566)
- [ ] clean up image files after tests (https://github.com/dhlab-basel/Sipi/issues/205)
- [ ] deployment and test packaging / codeship (PR #653)

#### Testing
- [ ] automated executon of `webapi` integration tests for `sipi`
- [ ] Jenkins server
- [ ] Load testing
- [ ] Include Salsah Tests in Travis-CI (#143)
    - [x] PR (#590)
    - [ ] Failing Salsah tests on travis (#596) 

### Finished
- [x] Admin additions #702 
- [x] Configure wich routes / versions can be used in Knora #639
- [x] Store an optional short code and multiple ontologies per project (#654) 
- [x] Add JSON Web Token Support (#171)
    - [x] PR #591 
    - [x] Add Salsah 2.0 token based authentication PR https://github.com/dhlab-basel/Salsah/pull/61

**Comment by subotic** [comment]
abandoned
